services:
  discord-ai-summarizer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-ai-summarizer
    restart: unless-stopped
    volumes:
      - ./data:/usr/src/app/data
      - ./.env:/usr/src/app/.env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    command: sh -c "if [ \"$$NODE_ENV\" = \"development\" ]; then npm run dev; else npm start; fi"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 